name: Certora

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        conf:
          - RegistryList

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Install Jq
        uses: sergeysova/jq-action@v2

      - name: Run Certora Config Linter
        run: |
          file="certora/confs/${{ matrix.conf }}.conf"
          diff <(grep -v "//" "$file" | jq) <(grep -v "//" "$file")

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: ">=3.10"

      - name: Install certora
        run: pip install certora-cli

      - name: Install solc (0.8.28)
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.28/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc-0.8.28

      - name: Verify ${{ matrix.conf }}
        run: certoraRun certora/confs/${{ matrix.conf }}.conf
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}